#!/bin/sh

# Online help for PHP stuff in vim.

# Needs cURL.

# This is some hacky shit, but eh.
# I don't care enough right now to optimize this.
# TODO: Care enough?

# The sites we're going to search on, and what we're searching for.
PHP=http://www.php.net/
DRUPAL=http://api.drupal.org/api/drupal/7/search/
GOOGLE=http://www.google.com/search?as_q=php%20
SEARCHTERM=$1
# You should also set an environment variable named BROWSER to your
# browser, e.g. chrome

function GetHTTPCode {
  # Gets back the HTTP response code.
  # drupal.org throws a 500 if you don't have a user agent.
  # I don't care if it's real or not. Sorry, drupal.org!
  curl -s -A "whatever" -w "%{http_code}\\n" "$1$2" -o /dev/null
}

function main {
  HTTP_STATUS_PHP=$(GetHTTPCode $PHP$SEARCHTERM)
  HTTP_STATUS_DRUPAL=$(GetHTTPCode $DRUPAL$SEARCHTERM)

  # If it's a good URL, awesome, it's on PHP.net.
  if [ $HTTP_STATUS_PHP -eq 200 ];
  then
    $BROWSER "$PHP$SEARCHTERM"
    exit
  # If we're redirecting from the search page, it's on drupal.org.
  elif [ $HTTP_STATUS_DRUPAL -eq 302 ];
  then
    $BROWSER "$DRUPAL$SEARCHTERM"
    exit
  # Fuck it, let's just Google it.
  else
    $BROWSER "$GOOGLE$SEARCHTERM"
    exit
  fi
}

main
